# Generated by Django 4.1 on 2022-12-06 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('usn', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100)),
                ('sem', models.IntegerField(default='')),
                ('phone', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
